version: "3.8"

services:
  ##
  # OpenVPN server
  #
  openvpn:
    image: ghcr.io/linuxserver/openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/openvpn/config/:/config/
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped

  ##
  # Watchtower Docker container updates
  #
  watchtower:
    image: containrrr/watchtower
    command: --schedule "0 0 1 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
