#cloud-config

fqdn: ${fqdn}
hostname: ${hostname}
manage_etc_hosts: true
timezone: Europe/Amsterdam
locale: C.UTF-8

ntp:
  enabled: true

users:
  - name: cloud
    gecos: Cloud User
    groups: docker
    # Generate a password using `mkpasswd --method=SHA-512 --rounds=4096`
    passwd: ${passwd}
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) ALL
    ssh_authorized_keys:
      - ${chomp(ssh_public_key)}

ssh_keys:
  rsa_public: ${chomp(sshd_public_key)}
  rsa_private: |
    ${indent(4, sshd_private_key)}

disk_setup:
  /dev/sda:
    table_type: mbr
    layout: [100]
    overwrite: false

fs_setup:
  - label: master
    filesystem: ext4
    device: /dev/sda
    partition: auto
    overwrite: false

mounts:
  - [ /dev/sda1, /data/, auto, "defaults,nofail,x-systemd.mount-timeout=10" ]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - fail2ban
  - ufw

package_update: true
package_upgrade: true
package_reboot_if_required: true

write_files:
  - content: |
      ${indent(6, docker_compose)}
    owner: "cloud:cloud"
    path: /app/openvpn/docker-compose.yml

runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable --now fail2ban
  # Configure firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw limit 22/tcp
  - ufw allow 943/tcp
  - ufw allow 9443/tcp
  - ufw allow 1194/udp
  - ufw enable
  # Configure SSH server
  - sed -i -e '/^#PermitRootLogin.*$/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 3/' /etc/ssh/sshd_config
  - sed -i -e '/^# *AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  # Install Docker
  - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
  - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable --now docker
  # Install Docker Compose
  - "curl -L 'https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64' -o /usr/local/bin/docker-compose"
  - chmod +x /usr/local/bin/docker-compose
  # Start application
  - chown -R cloud:cloud /app
  - sudo -u cloud docker-compose -f /app/openvpn/docker-compose.yml up -d

final_message: "The system is finally up, after $UPTIME seconds"
