#cloud-config

fqdn: ${fqdn}
hostname: ${hostname}
manage_etc_hosts: true
timezone: Europe/Berlin
locale: C.UTF-8

ntp:
  enabled: true

write_files:
  - path: /etc/network/interfaces.d/60-floating-ip
    content: |
      auto eth0:1
      iface eth0:1 inet static
          address ${ip_address}
          netmask 32

users:
  - name: cloud
    gecos: Cloud User
    groups: docker
    # Generate a password using `mkpasswd --method=SHA-512 --rounds=4096`
    passwd: ${passwd}
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) ALL
    ssh_authorized_keys:
      - ${chomp(ssh_public_key)}

ssh_keys:
  rsa_public: ${chomp(sshd_public_key)}
  rsa_private: |
    ${indent(4, sshd_private_key)}

mounts:
  - [ ${default_volume}, "/mnt/default/", "ext4", "defaults,discard", "0", "0" ]
  - [ "/mnt/default/docker/volumes/", "/var/lib/docker/volumes/", "none", "defaults,bind", "0", "0" ]

packages:
  - fail2ban
  - fuse
  - sshfs
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - jq
  - git

package_update: true
package_upgrade: true
package_reboot_if_required: true

runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable --now fail2ban
  - systemctl restart networking
  - tune2fs -m 0 ${default_volume}
  - chown cloud:cloud /mnt/default
  - mkdir -p /mnt/default/docker/volumes/
  - mount -a
  - rmdir /mnt/default/lost+found
  # Configure SSH server
  - sed -i -e '/^#HostKey /etc/ssh/ssh_host_rsa_key.*$/s/^.*$/#HostKey /etc/ssh/ssh_host_rsa_key/' /etc/ssh/sshd_config
  - sed -i -e '/^#PermitRootLogin.*$/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/#^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 3/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  # Install Docker
  - mkdir -p /etc/apt/keyrings
  - "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  - "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable' | tee /etc/apt/sources.list.d/docker.list"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable --now docker

final_message: "The system is finally up, after $UPTIME seconds"
