version: "3.8"

services:
  ##
  # Reverse proxy
  #
  traefik:
    image: traefik:v2.3
    command: >-
      --log.level=DEBUG
      --api.dashboard=true
      --providers.docker
      --providers.docker.watch=true
      --providers.docker.exposedbydefault=false
      --entrypoints.websecure.address=:443
      --entrypoints.web.address=:80
      --entrypoints.web.http.redirections.entryPoint.to=websecure
      --serverstransport.insecureskipverify=true
      --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=gandiv5
      --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      --certificatesresolvers.letsencrypt.acme.email=florian@floriandejonckheere.be
      --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
    env_file: .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/etc/traefik/acme/"
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.traefik-tls.redirectscheme.scheme: "https"
      traefik.http.middlewares.traefik-auth.basicauth.users: "${TRAEFIK_AUTH}"

      traefik.http.routers.traefik.rule: "Host(`traefik.cloud.dejonckhee.re`)"
      traefik.http.routers.traefik.entrypoints: "web"
      traefik.http.routers.traefik.middlewares: "traefik-tls"

      traefik.http.routers.traefik-tls.rule: "Host(`traefik.cloud.dejonckhee.re`)"
      traefik.http.routers.traefik-tls.service: "api@internal"
      traefik.http.routers.traefik-tls.entrypoints: "websecure"
      traefik.http.routers.traefik-tls.middlewares: "traefik-auth"
      traefik.http.routers.traefik-tls.tls: "true"
      traefik.http.routers.traefik-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.traefik.loadbalancer.server.port: "80"

      traefik.http.middlewares.secured.chain.middlewares: "traefik-tls,traefik-auth"

  ##
  # Web server
  #
  nginx:
    image: ghcr.io/linuxserver/nginx
    volumes:
      - "http:/srv/http/"
      - "nginx:/config/nginx/"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.nginx-tls.redirectscheme.scheme: "https"

      traefik.http.middlewares.nginx-redirect.redirectregex.regex: "^(https?://)([^/]*)/(.*)$$"
      traefik.http.middlewares.nginx-redirect.redirectregex.replacement: "$${1}florian.dejonckhee.re/$${3}"

      traefik.http.routers.nginx.rule: "Host(`florian.dejonckhee.re`, `dejonckhee.re`, `floriandejonckheere.be`, `www.floriandejonckheere.be`)"
      traefik.http.routers.nginx.entrypoints: "web"
      traefik.http.routers.nginx.middlewares: "nginx-tls"

      traefik.http.routers.nginx-redirect.rule: "Host(`dejonckhee.re`, `floriandejonckheere.be`, `www.floriandejonckheere.be`)"
      traefik.http.routers.nginx-redirect.entrypoints: "websecure"
      traefik.http.routers.nginx-redirect.tls: "true"
      traefik.http.routers.nginx-redirect.tls.domains[0].main: "dejonckhee.re"
      traefik.http.routers.nginx-redirect.tls.domains[0].sans: "floriandejonckheere.be,www.floriandejonckheere.be"
      traefik.http.routers.nginx-redirect.middlewares: "nginx-redirect"
      traefik.http.routers.nginx-redirect.tls.certresolver: "letsencrypt"

      traefik.http.routers.nginx-tls.rule: "Host(`florian.dejonckhee.re`)"
      traefik.http.routers.nginx-tls.entrypoints: "websecure"
      traefik.http.routers.nginx-tls.tls: "true"
      traefik.http.routers.nginx-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.nginx.loadbalancer.server.port: "80"

  ##
  # Database
  #
  postgres:
    image: postgres:12-alpine
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    restart: on-failure

  ##
  # Password manager
  #
  bitwarden:
    image: bitwardenrs/server:alpine
    env_file: bitwarden.env
    volumes:
      - "bitwarden:/data/"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.bitwarden-tls.redirectscheme.scheme: "https"

      traefik.http.routers.bitwarden.rule: "Host(`vault.dejonckhee.re`)"
      traefik.http.routers.bitwarden.entrypoints: "web"
      traefik.http.routers.bitwarden.middlewares: "bitwarden-tls"

      traefik.http.routers.bitwarden-tls.rule: "Host(`vault.dejonckhee.re`)"
      traefik.http.routers.bitwarden-tls.entrypoints: "websecure"
      traefik.http.routers.bitwarden-tls.tls: "true"
      traefik.http.routers.bitwarden-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.bitwarden.loadbalancer.server.port: "80"

volumes:
  acme:
  http:
  nginx:
  postgres:
  bitwarden:
