version: '3.4'

services:
  ##
  # Web server container
  #
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/:/etc/nginx/
      - /srv/http/:/srv/http/
      - letsencrypt:/letsencrypt/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    network_mode: host
    labels:
      - sh.acme.autoload.domain=florian.dejonckhee.re
    restart: always

  ##
  # ACME.sh container
  #
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - ./acmeout/:/acme.sh/
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt/
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=florian.dejonckhee.re
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/florian.dejonckhee.re/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/florian.dejonckhee.re/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/florian.dejonckhee.re/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/florian.dejonckhee.re/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"

  ##
  # Resilio Sync container
  #
  rslsync:
    image: resilio/sync
    volumes:
      - /srv/sync/:/mnt/sync/
    ports:
      - "127.0.0.1:8888:8888"
      - "0.0.0.0:55555:55555"
    restart: always

  ##
  # Database container
  #
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

volumes:
  letsencrypt:
  postgres:
