version: '3.4'

services:
  ##
  # Web server container
  #
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/:/etc/nginx/
      - /srv/http/:/srv/http/
      - letsencrypt:/etc/letsencrypt/
      - letsencrypt-data:/etc/letsencrypt-data/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: always

  ##
  # Let's Encrypt container
  #
  certbot:
    build: certbot
    volumes:
      - ./certbot/certbot.sh:/certbot.sh
      - letsencrypt:/etc/letsencrypt/
      - letsencrypt-data:/etc/letsencrypt-data/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx
    restart: always

  ##
  # Resilio Sync container
  #
  rslsync:
    image: resilio/sync
    volumes:
      - /srv/sync/:/mnt/sync/
    ports:
      - "127.0.0.1:8888:8888"
      - "0.0.0.0:55555:55555"
    restart: always

  ##
  # Database container
  #
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

volumes:
  # Let's Encrypt certificates
  letsencrypt:
  # Let's Encrypt challenges
  letsencrypt-data:
  # Database
  postgres:
