version: '3.4'

services:
  ##
  # Web server container
  #
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/
      - ./logs/nginx/:/logs/
      - http:/srv/http/
      - torrents:/srv/torrents/
      - letsencrypt:/etc/letsencrypt/
      - letsencrypt-data:/etc/letsencrypt-data/
      - nextcloud:/srv/nextcloud:ro
    links:
      - registry
      - rslsync
      - trivial
      - bitwarden
      - nextcloud
      - jellyfin
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: always

  ##
  # Let's Encrypt container
  #
  certbot:
    build: certbot
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    volumes:
      - ./certbot/certbot.sh:/certbot.sh
      - letsencrypt:/etc/letsencrypt/
      - letsencrypt-data:/etc/letsencrypt-data/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx
    restart: always

  ##
  # Resilio Sync container
  #
  rslsync:
    image: linuxserver/resilio-sync
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - rslsync:/config
      - rslsync_data:/sync
    ports:
      - "0.0.0.0:55555:55555"
    restart: always

  ##
  # Database container
  #
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  ##
  # Container registry
  #
  registry:
    image: registry:2
    volumes:
      - registry:/var/lib/registry
    ports:
      - "127.0.0.1:5000:5000"
    restart: always

  ##
  # Trivial
  #
  trivial:
    image: registry.dejonckhee.re/trivial
    volumes:
      - ./logs/trivial/:/app/log/
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY_BASE=mybase
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trivial
      - POSTGRES_USER=trivial
      - POSTGRES_PASS=trivial
    restart: always

  ##
  # Bitwarden Server
  #
  bitwarden:
    image: bitwardenrs/server-postgresql:1.13.1
    volumes:
      - bitwarden:/data
    depends_on:
      - postgres
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      DATABASE_URL: "postgresql://bitwarden:bitwarden@postgres/bitwarden"
      ENABLE_DW_WAL: "false"
    restart: always

  ##
  # Redis
  #
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  ##
  # NextCloud
  #
  nextcloud:
    build: nextcloud
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    depends_on:
      - postgres
      - redis
    volumes:
      - nextcloud:/var/www/html
      - rslsync:/mnt/rslsync:ro
      - torrents:/mnt/torrents:ro
      - http:/mnt/http
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    restart: always

  ##
  # qBittorrent
  #
  torrents:
    image: linuxserver/qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - qbittorrent:/config
      - torrents:/downloads
      - jellyfin_data:/downloads/Jellyfin
    ports:
      - "0.0.0.0:6881:6881"
      - "0.0.0.0:6881:6881/udp"
      - "127.0.0.1:8080:8080"
    restart: always

  ##
  # WireGuard
  #
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    volumes:
      - wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - "0.0.0.0:51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      SERVERURL: dejonckhee.re
      PEERS: 5
    restart: always

  ##
  # Minecraft
  #
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraft:/data
    ports:
      - "0.0.0.0:25565:25565"
    environment:
      EULA: "TRUE"
      TZ: Europe/Berlin
      VERSION: 1.13.2
    restart: always

  ##
  # Borgmatic backups
  #
  borgmatic:
    image: b3vis/borgmatic
    volumes:
      - /data:/mnt/source:ro
      - /data/backup:/mnt/borg-repository
      - ./borgmatic/borgmatic.d/:/etc/borgmatic.d/
      - ./borgmatic/.config/borg/:/root/.config/borg/
      - /root/.ssh/:/root/.ssh/
      - borgmatic:/root/.cache/borg/
    environment:
      TZ: Europe/Brussels
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
    restart: always

  ##
  # Watchtower Docker container updates
  #
  watchtower:
    image: containrrr/watchtower
    command: --schedule "0 0 1 * * *" --notifications email
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/florian/.docker/config.json:/config.json
    environment:
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
    restart: always

  ##
  # MusicBrainz mirror
  #
  mbdata:
    build: mbdata
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    depends_on:
      - postgres
    volumes:
      - ./mbdata/mbslave.conf:/etc/mbslave.conf
    environment:
      MBSLAVE_CONFIG: /etc/mbslave.conf
    restart: always

  ##
  # Jellyfin
  #
  jellyfin:
    image: linuxserver/jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - jellyfin:/config
      - jellyfin_data:/data
    devices:
      - /dev/dri:/dev/dri
    restart: always

volumes:
  # Let's Encrypt certificates
  letsencrypt:
  # Let's Encrypt challenges
  letsencrypt-data:
  # Resilio Sync
  rslsync:
  rslsync_data:
  # Database
  postgres:
  # Docker registry data
  registry:
  # Bitwarden data
  bitwarden:
  # Redis data
  redis:
  # Nextcloud data
  nextcloud:
  # Static HTTP data
  http:
  # qBittorrent config
  qbittorrent:
  # Torrents
  torrents:
  # WireGuard
  wireguard:
  # Minecraft
  minecraft:
  # Borgmatic
  borgmatic:
  # Jellyfin
  jellyfin:
  jellyfin_data:
