version: "3.8"

services:
  ##
  # Password manager
  #
  rslsync:
    image: ghcr.io/linuxserver/resilio-sync
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - rslsync:/config
      - rslsync_data:/sync
    ports:
      - "55555:55555"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.rslsync-tls.redirectscheme.scheme: "https"

        traefik.http.routers.rslsync.rule: "Host(`sync.dejonckhee.re`)"
        traefik.http.routers.rslsync.entrypoints: "web"
        traefik.http.routers.rslsync.middlewares: "rslsync-tls"

        traefik.http.routers.rslsync-tls.rule: "Host(`sync.dejonckhee.re`)"
        traefik.http.routers.rslsync-tls.entrypoints: "websecure"
        traefik.http.routers.rslsync-tls.tls: "true"
        traefik.http.routers.rslsync-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.rslsync.loadbalancer.server.port: "8888"
        traefik.docker.network: "traefik_proxy"

volumes:
  rslsync:
  rslsync_data:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
