version: "3.8"

services:
  ##
  # Database
  #
  postgres:
    image: postgres:12-alpine
    volumes:
      - "data:/var/lib/postgresql/data/"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure

volumes:
  data:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
