version: "3.8"

services:
  prune:
    image: alpinelinux/docker-cli
    command: sh -c "while true; do docker system prune --all --force; sleep 86400; done"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
