version: "3"

services:
  ##
  # Reverse proxy
  #
  traefik:
    image: traefik:v2.3
    command: >-
      --api.insecure=true
      --providers.docker
      --providers.docker.swarmmode=true
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --certificatesresolvers.letsencryptresolver.acme.email=florian@floriandejonckheere.be
      --certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/acme/acme.json
      --certificatesresolvers.letsencryptresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      --certificatesresolvers.letsencryptresolver.acme.httpchallenge=true
      --certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "acme:/etc/traefik/acme/"
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure

volumes:
  acme:
