version: "3.8"

services:
  ##
  # Minecraft
  #
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - "data:/data"
    ports:
      - "0.0.0.0:25565:25565"
    networks:
      - proxy
    environment:
      SERVER_NAME: Thalarion
      MOTD: Welcome to Thalarion MC server
      DIFFICULTY: easy
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: DeathByCookie,shitbrix
      OPS: DeathByCookie,shitbrix
      MAX_PLAYERS: 20
      ONLINE_MODE: "TRUE"
      # Check latest version on https://www.minecraft.net/en-us/download/server
      VERSION: 1.16.4
      MEMORY: 13G
      LEVEL: 20200601
      EULA: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      USE_LARGE_PAGES: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      UID: 1000
      GID: 1000
      TZ: Europe/Berlin
    deploy:
      placement:
        constraints:
          - node.hostname==minecraft
      restart_policy:
        condition: on-failure

volumes:
  data:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
