version: "3.8"

services:
  ##
  # Res Triviales
  #
  trivial:
    image: ghcr.io/floriandejonckheere/trivial-app:v4.1.0
    env_file: trivial.env
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.trivial-tls.redirectscheme.scheme: "https"

        traefik.http.routers.trivial.rule: "Host(`trivial.dejonckhee.re`)"
        traefik.http.routers.trivial.entrypoints: "web"
        traefik.http.routers.trivial.middlewares: "trivial-tls"

        traefik.http.routers.trivial-tls.rule: "Host(`trivial.dejonckhee.re`)"
        traefik.http.routers.trivial-tls.entrypoints: "websecure"
        traefik.http.routers.trivial-tls.tls: "true"
        traefik.http.routers.trivial-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.trivial.loadbalancer.server.port: "3000"
        traefik.docker.network: "traefik_proxy"

volumes:
  trivial:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
