version: "3.8"

services:
  ##
  # Identity management
  #
  authelia:
    image: authelia/authelia
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /config/ldap_password
      AUTHELIA_JWT_SECRET_FILE: /config/jwt_secret
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /config/postgres_password
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/smtp_password
      TZ: Europe/Berlin
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.authelia-tls.redirectscheme.scheme: "https"

        traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:9091/api/verify?rd=https://auth.dejonckhee.re/"
        traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
        traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User, Remote-Groups, Remote-Name, Remote-Email"

        traefik.http.routers.authelia.rule: "Host(`auth.dejonckhee.re`)"
        traefik.http.routers.authelia.entrypoints: "web"
        traefik.http.routers.authelia.middlewares: "authelia-tls"

        traefik.http.routers.authelia-tls.rule: "Host(`auth.dejonckhee.re`)"
        traefik.http.routers.authelia-tls.entrypoints: "websecure"
        traefik.http.routers.authelia-tls.tls: "true"
        traefik.http.routers.authelia-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.authelia.loadbalancer.server.port: "9091"
        traefik.docker.network: "traefik_proxy"
    configs:
      - source: config_7
        target: /config/configuration.yml
      - source: ldap_password_1
        target: /config/ldap_password
        mode: 0600
      - source: jwt_secret_1
        target: /config/jwt_secret
        mode: 0600
      - source: postgres_password_1
        target: /config/postgres_password
        mode: 0600
      - source: smtp_password_1
        target: /config/smtp_password
        mode: 0600

configs:
  config_7:
    file: authelia.yml
  ldap_password_1:
    file: ldap.secret
  jwt_secret_1:
    file: jwt_secret.secret
  postgres_password_1:
    file: postgres.secret
  smtp_password_1:
    file: smtp.secret

networks:
  proxy:
    external: true
    name: "traefik_proxy"
