version: "3.8"

services:
  ##
  # HTTP server
  #
  nginx:
    image: ghcr.io/linuxserver/nginx
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - "cache:/cache/"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.metal-archives-tls.redirectscheme.scheme: "https"

        traefik.http.routers.metal-archives.rule: "Host(`ma.cache.headbang.re`)"
        traefik.http.routers.metal-archives.entrypoints: "web"
        traefik.http.routers.metal-archives.middlewares: "metal-archives-tls"

        traefik.http.routers.metal-archives-tls.rule: "Host(`ma.cache.headbang.re`)"
        traefik.http.routers.metal-archives-tls.entrypoints: "websecure"
        traefik.http.routers.metal-archives-tls.tls: "true"
        traefik.http.routers.metal-archives-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.metal-archives.loadbalancer.server.port: "80"
        traefik.docker.network: "traefik_proxy"
    configs:
      - source: config_2
        target: /config/nginx/nginx.conf
      - source: client_key_1
        target: /config/client.key
      - source: client_cert_1
        target: /config/client.pem

configs:
  config_2:
    file: nginx.conf
  client_key_1:
    file: key.secret
  client_cert_1:
    file: cert.secret

volumes:
  cache:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
