- name: Check if resource is created
  shell: terraform state list {{ vars.resource }}
  args:
    chdir: ../terraform
  register: resource_status
  ignore_errors: true
  tags: swarm

- name: Create resource
  when: resource_status.rc != 0
  shell: terraform apply -target={{ vars.module }} -var {{ vars.variable }}=true
  args:
    chdir: ../terraform
