- name: Check if resource is destroyed
  shell: terraform state list {{ vars.resource }}
  args:
    chdir: ../terraform
  register: resource_status
  ignore_errors: true
  tags: swarm

- name: Destroy resource
  when: resource_status.rc == 0
  shell: terraform apply -target={{ vars.module }} -var {{ vars.variable }}=false
  args:
    chdir: ../terraform
