version: "3.8"

services:
  ##
  # Backup
  #
  borgmatic:
    image: b3vis/borgmatic
    env_file: borgmatic.env
    environment:
      TZ: Europe/Berlin
    volumes:
      - "/mnt/default/:/mnt/source/:ro"
      - "config:/root/.config/borg/"
      - "cache:/root/.cache/borg/"
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
    configs:
      - source: config_5
        target: /etc/borgmatic.d/config.yaml
      - source: crontab_1
        target: /etc/borgmatic.d/crontab.txt
      - source: ssh_key_1
        target: /root/.ssh/id_rsa
        mode: 0400
      - source: known_hosts_1
        target: /root/.ssh/known_hosts

configs:
  config_5:
    file: borgmatic.yml
  crontab_1:
    file: crontab.txt
  ssh_key_1:
    file: $HOME/.ssh/web-backup
  known_hosts_1:
    file: known_hosts

volumes:
  config:
  cache:
