version: "3.8"

services:
  ##
  # OpenVPN server
  #
  openvpn:
    image: ghcr.io/linuxserver/openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/default/openvpn/:/config/
    ports:
      - "943:943"
      - "9443:9443"
      - "1194:1194/udp"
    deploy:
      placement:
        constraints:
          - node.hostname==vpn
      restart_policy:
        condition: on-failure
