- name: Check if Swarm is already initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Add managers to the Swarm
  shell: "docker swarm join --token {{ hostvars['swarm_manager']['manager_token']['stdout'] }} {{ hostvars['swarm_manager']['ansible_default_ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0
  tags: swarm
